name = "mapquiz-api"
main = "src/index.js"
compatibility_date = "2024-11-01"

# Created by `wrangler d1 create mapquiz`. Paste the printed database_id below.
[[d1_databases]]
binding = "DB"
database_name = "mapquiz"
database_id = "374a5d93-0779-4fb0-b062-8f04218f1ca4"
